import { NextRequest, NextResponse } from 'next/server';
import { getMarketForecast, COMMODITY_PROFILES } from '@/lib/marketForecaster';

/**
 * GET /api/market-forecast
 * Query Params: crop (string, optional)
 * 
 * Takes a crop name and returns 60 days of historical data along with 
 * a 30-day future price prediction generated by a custom Time-Series ML model.
 * If no crop parameter is passed, returns the list of supported commodities.
 */
export async function GET(request: NextRequest) {
    try {
        const { searchParams } = new URL(request.url);
        const crop = searchParams.get('crop');

        if (!crop) {
            return NextResponse.json({
                commodities: Object.values(COMMODITY_PROFILES).map(c => ({
                    key: c.key,
                    name: c.name,
                    category: c.category,
                    msp: c.msp,
                    mandiHub: c.mandiHub
                }))
            });
        }

        // Run the Time-Series Forecasting ML Algorithm (Holt-Winters Damped Trend)
        const forecastData = getMarketForecast(crop);

        return NextResponse.json({
            source: 'custom_time_series_ml',
            message: `Market forecast generated for ${forecastData.commodity.name} using Holt-Winters Damped Trend Engine.`,
            data: forecastData
        });

    } catch (error) {
        console.error('Market Forecaster API Error:', error);
        return NextResponse.json({ 
            error: 'Failed to generate market forecast',
            details: error instanceof Error ? error.message : 'Unknown error'
        }, { status: 500 });
    }
}
