'use client';

import { useEffect, useMemo, useState } from 'react';

export type SiteLanguageCode = 'en' | 'hi' | 'mr' | 'ta' | 'te' | 'kn' | 'bn' | 'pa';

const APP_LANGUAGE_KEY = 'appLanguage';
const APP_SETTINGS_KEY = 'appSettings';
export const APP_LANGUAGE_EVENT = 'app-language-change';

const LANGUAGE_LABELS: Record<SiteLanguageCode, string> = {
  en: 'English',
  hi: 'हिंदी (Hindi)',
  mr: 'मराठी (Marathi)',
  pa: 'ਪੰਜਾਬੀ (Punjabi)',
  ta: 'தமிழ் (Tamil)',
  te: 'తెలుగు (Telugu)',
  kn: 'ಕನ್ನಡ (Kannada)',
  bn: 'বাংলা (Bengali)',
};

const HTML_LANG_CODES: Record<SiteLanguageCode, string> = {
  en: 'en',
  hi: 'hi',
  mr: 'mr',
  pa: 'pa',
  ta: 'ta',
  te: 'te',
  kn: 'kn',
  bn: 'bn',
};

const UI_TEXT: Record<SiteLanguageCode, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    advisory: 'Advisory',
    weather: 'Weather',
    market: 'Market',
    yojana: 'Yojana Sahayak',
    myDashboard: 'My Dashboard',
    login: 'Login',
    overview: 'Overview',
    analytics: 'Analytics',
    myFarm: 'My Farm',
    cropCalendar: 'Crop Calendar',
    cropAdvisory: 'Crop Advisory',
    fertilizerCalc: 'Fertilizer Calculator',
    voiceAssistant: 'Voice Q&A',
    plantDoctor: 'Plant Doctor',
    marketPrices: 'Market Prices',
    govtSchemes: 'Govt Schemes',
    msp: 'Minimum Support Price',
    communityForum: 'Community Forum',
    soilLabs: 'Soil Labs',

    yieldPredictor: 'Yield Predictor',
    agriShorts: 'Agri Shorts',
    cropLifecycle: 'Crop Lifecycle',
    traceability: 'Traceability',
    settings: 'Settings',
    signOut: 'Sign Out',
    signingOut: 'Signing Out...',
    platform: 'Platform',
    resources: 'Resources',
    contact: 'Contact',
    aiAdvisory: 'AI Advisory',
    weatherForecast: 'Weather Forecast',
    farmingBlog: 'Farming Blog',
    cropGuides: 'Crop Guides',
    community: 'Community',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    notifications: 'Notifications',
    unread: 'unread',
    markAllRead: 'Mark all as read',
    office: 'Office:',
    empowering: 'Empowering farmers with AI-driven insights for a sustainable and profitable future.',
    aiPoweredFarmingAssistant: 'AI-Powered Farming Assistant',
    farmingMade: 'Farming made',
    smarterBetter: 'Smarter & Better',
    heroSubtitle: 'Empower your agriculture with real-time AI insights. Get precision weather forecasts, soil health analysis, and market trends instantly.',
    startForFree: 'Start for Free',
    signIn: 'Sign In',
    verifiedData: 'Verified Data',
    accuracy95: '95% Accuracy',
    cropHealthCard: 'Crop Health',
    wheatField2: 'Wheat Field #2',
    nitrogenLevel: 'Nitrogen Level',
    optimalRange: 'Optimal Range',
    temp: 'Temp',
    sunny: 'Sunny',
    pestRisk: 'Pest Risk',
    lowSafe: 'Low (Safe)',
    marketPrice: 'Market Price',
    coreModules: 'Core Modules',
    everythingYouNeed: 'Everything you need to',
    farmSmarter: 'farm smarter',
    featuresSubtitle: 'Comprehensive tools designed specifically for small and marginal farmers to maximize yield and profit using cutting-edge AI technology.',
    openFeature: 'Open Feature',
    weatherIntelligence: 'Weather Forecast System',
    weatherIntelligenceDesc: 'Daily forecast, Rain alerts, Temperature updates, and Storm warnings.',
    cropCalendarFeat: 'Crop Calendar',
    cropCalendarFeatDesc: 'Avoid missing farming schedules with sowing reminders, fertilizer schedule, and harvest reminders.',
    smartIrrigation: 'Smart Irrigation Guidance',
    smartIrrigationDesc: 'Prevent water wastage with an irrigation schedule, soil moisture tracking, and water requirement calculator.',
    loanEligibility: 'Loan Eligibility Checker',
    loanEligibilityDesc: 'Income analysis, Loan recommendations, and EMI calculator.',
    soilHealthEngine: 'Soil Health Engine',
    soilHealthEngineDesc: 'Upload soil reports to get personalized nutrient and fertilizer recommendations.',
    marketPriceDashboard: 'Market Price Dashboard',
    marketPriceDashboardDesc: 'Live Mandi prices and trend visualization for better selling decisions.',
    pestDiseaseDiagnosis: 'Pest & Disease Diagnosis',
    pestDiseaseDiagnosisDesc: 'AI-powered image analysis to identify crop diseases and suggest treatments.',
    multilingualSupport: 'Multilingual Support',
    multilingualSupportDesc: 'Access advisory in Hindi, Tamil, Telugu, and other regional languages.',
    cropHealthMonitoring: 'Crop Health Monitoring',
    cropHealthMonitoringDesc: 'Track crop growth stages and receive timely interventions.',
    farmersEmpowered: 'Farmers Empowered',
    acresMonitored: 'Acres Monitored',
    yieldIncrease: 'Yield Increase',
    waterSaved: 'Water Saved',
    aerospaceTechnology: 'Aerospace Technology',
    intelligenceBehind: 'Intelligence behind',
    everyHarvest: 'every harvest',
    advancedSubtitle: 'We leverage state-of-the-art AI, IoT sensors, and satellite remote sensing to bring precision agriculture directly to the field. Our algorithms process terabytes of data to provide local insights.',
    exploreEngine: 'Explore The Engine',
    deepLearningModels: 'Deep Learning Models',
    deepLearningModelsDesc: 'Our proprietary CNNs analyze crop images with 98% accuracy to detect early signs of disease and nutrient deficiency.',
    satelliteRemoteSensing: 'Satellite Remote Sensing',
    satelliteRemoteSensingDesc: 'Integration with Sentinel-2 and Landsat data provides macro-level insights on vegetation indices (NDVI) and soil moisture.',
    bigDataAnalytics: 'Big Data Analytics',
    bigDataAnalyticsDesc: 'Processing terabytes of historical weather and yield data to generate hyper-local predictive models for your farm.',
    iotConnectivity: 'IoT Connectivity',
    iotConnectivityDesc: 'Seamlessly connect with smart soil sensors and automated irrigation systems for a fully autonomous farm management experience.',
    howItWorksTitle: 'How it works',
    howItWorksSubtitle: 'Get expert advisory in three simple steps. No complex setup required.',
    uploadData: 'Upload Data',
    uploadDataDesc: 'Simply take a photo of your crop or soil report and upload it to our secure platform.',
    aiAnalysis: 'AI Analysis',
    aiAnalysisDesc: 'Our advanced AI analyzes your data against millions of data points to identify issues.',
    getResults: 'Get Results',
    getResultsDesc: 'Receive instant, actionable advice in your local language to improve your yield.',
    joinAgriRevolution: 'Join the Agriculture Revolution',
    readyToTransform: 'Ready to transform',
    yourHarvest: 'your harvest?',
    howItWorksCtaSubtitle: 'Empower your farming journey with AI insights. Over 2.8 lakh farmers are already growing smarter with SmartAgriSense.',
    getStartedForFree: 'Get Started for Free',
    contactRuralAdvisors: 'Contact Rural Advisors',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    advisory: 'सलाह',
    weather: 'मौसम',
    market: 'बाजार',
    yojana: 'योजना सहायक',
    myDashboard: 'मेरा डैशबोर्ड',
    login: 'लॉगिन',
    overview: 'सारांश',
    analytics: 'विश्लेषण',
    myFarm: 'मेरा खेत',
    cropCalendar: 'फसल कैलेंडर',
    cropAdvisory: 'फसल सलाह',
    voiceAssistant: 'वॉइस प्रश्नोत्तर',
    plantDoctor: 'पौधा डॉक्टर',
    marketPrices: 'मंडी भाव',
    govtSchemes: 'सरकारी योजनाएं',
    msp: 'न्यूनतम समर्थन मूल्य',
    communityForum: 'समुदाय मंच',
    soilLabs: 'मृदा लैब',
    fertilizerCalc: 'उर्वरक कैलकुलेटर',
    yieldPredictor: 'उपज भविष्यवाणी',
    agriShorts: 'कृषि शॉर्ट्स',
    cropLifecycle: 'फसल जीवनचक्र',
    traceability: 'पारदर्शिता',
    settings: 'सेटिंग्स',
    signOut: 'साइन आउट',
    signingOut: 'साइन आउट हो रहा है...',
    platform: 'प्लेटफॉर्म',
    resources: 'संसाधन',
    contact: 'संपर्क',
    aiAdvisory: 'एआई सलाह',
    weatherForecast: 'मौसम पूर्वानुमान',
    farmingBlog: 'खेती ब्लॉग',
    cropGuides: 'फसल गाइड',
    community: 'समुदाय',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    notifications: 'सूचनाएं',
    unread: 'अपठित',
    markAllRead: 'सभी को पढ़ा हुआ चिह्नित करें',
    office: 'कार्यालय:',
    empowering: 'किसानों को टिकाऊ और लाभकारी भविष्य के लिए एआई आधारित जानकारी से सशक्त बनाना।',
    aiPoweredFarmingAssistant: 'एआई-संचालित खेती सहायक',
    farmingMade: 'खेती बने',
    smarterBetter: 'अधिक स्मार्ट और बेहतर',
    heroSubtitle: 'रीयल-टाइम एआई जानकारी के साथ अपनी खेती को सशक्त बनाएं। सटीक मौसम पूर्वानुमान, मिट्टी स्वास्थ्य विश्लेषण और बाजार रुझान तुरंत पाएं।',
    startForFree: 'मुफ्त में शुरू करें',
    signIn: 'साइन इन',
    verifiedData: 'सत्यापित डेटा',
    accuracy95: '95% सटीकता',
    cropHealthCard: 'फसल स्वास्थ्य',
    wheatField2: 'गेहूं खेत #2',
    nitrogenLevel: 'नाइट्रोजन स्तर',
    optimalRange: 'उत्तम सीमा',
    temp: 'तापमान',
    sunny: 'धूप',
    pestRisk: 'कीट जोखिम',
    lowSafe: 'कम (सुरक्षित)',
    marketPrice: 'बाजार भाव',
    coreModules: 'मुख्य मॉड्यूल',
    everythingYouNeed: 'स्मार्ट खेती के लिए',
    farmSmarter: 'आपको चाहिए सब कुछ',
    featuresSubtitle: 'छोटे और सीमांत किसानों के लिए विशेष रूप से बने व्यापक उपकरण, जो उन्नत एआई की मदद से उत्पादन और लाभ बढ़ाते हैं।',
    openFeature: 'फ़ीचर खोलें',
    weatherIntelligence: 'मौसम इंटेलिजेंस',
    weatherIntelligenceDesc: 'सिंचाई और कीट प्रकोप के लिए रीयल-टाइम पूर्वानुमान और चेतावनियां।',
    soilHealthEngine: 'मिट्टी स्वास्थ्य इंजन',
    soilHealthEngineDesc: 'मिट्टी रिपोर्ट अपलोड करें और व्यक्तिगत पोषक व उर्वरक सुझाव पाएं।',
    marketPriceDashboard: 'बाजार भाव डैशबोर्ड',
    marketPriceDashboardDesc: 'बेहतर बिक्री निर्णय के लिए लाइव मंडी भाव और रुझान विश्लेषण।',
    pestDiseaseDiagnosis: 'कीट व रोग पहचान',
    pestDiseaseDiagnosisDesc: 'एआई आधारित इमेज विश्लेषण से फसल रोग पहचानें और उपचार सुझाव पाएं।',
    multilingualSupport: 'बहुभाषी समर्थन',
    multilingualSupportDesc: 'हिंदी, तमिल, तेलुगु और अन्य क्षेत्रीय भाषाओं में सलाह प्राप्त करें।',
    cropHealthMonitoring: 'फसल स्वास्थ्य निगरानी',
    cropHealthMonitoringDesc: 'फसल वृद्धि चरणों को ट्रैक करें और समय पर हस्तक्षेप पाएं।',
    farmersEmpowered: 'सशक्त किसान',
    acresMonitored: 'निगरानी किए गए एकड़',
    yieldIncrease: 'उत्पादन वृद्धि',
    waterSaved: 'जल बचत',
    aerospaceTechnology: 'एयरोस्पेस तकनीक',
    intelligenceBehind: 'हर फसल के पीछे',
    everyHarvest: 'तकनीकी बुद्धिमत्ता',
    advancedSubtitle: 'हम अत्याधुनिक एआई, आईओटी सेंसर और सैटेलाइट रिमोट सेंसिंग का उपयोग करके सटीक कृषि को खेत तक लाते हैं। हमारे एल्गोरिदम स्थानीय जानकारी देने के लिए विशाल डेटा प्रोसेस करते हैं।',
    exploreEngine: 'इंजन जानें',
    deepLearningModels: 'डीप लर्निंग मॉडल',
    deepLearningModelsDesc: 'हमारे विशेष CNN मॉडल 98% सटीकता से फसल तस्वीरों का विश्लेषण कर बीमारी और पोषक कमी के शुरुआती संकेत पहचानते हैं।',
    satelliteRemoteSensing: 'सैटेलाइट रिमोट सेंसिंग',
    satelliteRemoteSensingDesc: 'Sentinel-2 और Landsat डेटा से वनस्पति सूचकांक (NDVI) और मिट्टी नमी की व्यापक जानकारी मिलती है।',
    bigDataAnalytics: 'बिग डेटा एनालिटिक्स',
    bigDataAnalyticsDesc: 'ऐतिहासिक मौसम और उत्पादन डेटा के विशाल विश्लेषण से आपके खेत के लिए हाइपर-लोकल भविष्यवाणी मॉडल बनाए जाते हैं।',
    iotConnectivity: 'आईओटी कनेक्टिविटी',
    iotConnectivityDesc: 'स्मार्ट मिट्टी सेंसर और स्वचालित सिंचाई प्रणालियों से सहज कनेक्शन कर पूर्ण स्मार्ट फार्म प्रबंधन सक्षम करें।',
    howItWorksTitle: 'यह कैसे काम करता है',
    howItWorksSubtitle: 'तीन आसान चरणों में विशेषज्ञ सलाह पाएं। किसी जटिल सेटअप की जरूरत नहीं।',
    uploadData: 'डेटा अपलोड करें',
    uploadDataDesc: 'अपनी फसल या मिट्टी रिपोर्ट की फोटो लेकर हमारे सुरक्षित प्लेटफॉर्म पर अपलोड करें।',
    aiAnalysis: 'एआई विश्लेषण',
    aiAnalysisDesc: 'हमारा उन्नत एआई लाखों डेटा बिंदुओं से तुलना करके समस्याएं पहचानता है।',
    getResults: 'परिणाम पाएं',
    getResultsDesc: 'अपनी स्थानीय भाषा में तुरंत और उपयोगी सलाह पाएं ताकि उत्पादन बढ़े।',
    joinAgriRevolution: 'कृषि क्रांति से जुड़ें',
    readyToTransform: 'क्या आप बदलने के लिए तैयार हैं',
    yourHarvest: 'अपनी फसल?',
    howItWorksCtaSubtitle: 'एआई जानकारी के साथ अपनी खेती यात्रा को सशक्त बनाएं। 2.8 लाख से अधिक किसान पहले से SmartAgriSense के साथ बेहतर खेती कर रहे हैं।',
    getStartedForFree: 'मुफ्त में शुरू करें',
    contactRuralAdvisors: 'ग्रामीण सलाहकारों से संपर्क करें',
  },
  mr: {
    dashboard: 'डॅशबोर्ड',
    advisory: 'सल्ला',
    weather: 'हवामान',
    market: 'बाजार',
    yojana: 'योजना सहाय्यक',
    myDashboard: 'माझा डॅशबोर्ड',
    login: 'लॉगिन',
    overview: 'आढावा',
    analytics: 'विश्लेषण',
    myFarm: 'माझे शेत',
    cropCalendar: 'पीक कॅलेंडर',
    cropAdvisory: 'पीक सल्ला',
    voiceAssistant: 'व्हॉइस प्रश्नोत्तर',
    plantDoctor: 'पीक डॉक्टर',
    marketPrices: 'बाजारभाव',
    govtSchemes: 'शासकीय योजना',
    msp: 'किमान आधारभूत किंमत',
    communityForum: 'समुदाय मंच',
    soilLabs: 'माती प्रयोगशाळा',
    fertilizerCalc: 'खत गणक',
    yieldPredictor: 'उत्पन्न अंदाज',
    agriShorts: 'कृषी शॉर्ट्स',
    cropLifecycle: 'पीक जीवनचक्र',
    traceability: 'पारदर्शकता',
    settings: 'सेटिंग्स',
    signOut: 'साइन आउट',
    signingOut: 'साइन आउट सुरू आहे...',
    platform: 'प्लॅटफॉर्म',
    resources: 'संसाधने',
    contact: 'संपर्क',
    aiAdvisory: 'एआय सल्ला',
    weatherForecast: 'हवामान अंदाज',
    farmingBlog: 'शेती ब्लॉग',
    cropGuides: 'पीक मार्गदर्शक',
    community: 'समुदाय',
    privacyPolicy: 'गोपनीयता धोरण',
    termsOfService: 'सेवेच्या अटी',
    notifications: 'सूचना',
    unread: 'न वाचलेल्या',
    markAllRead: 'सर्व वाचले म्हणून चिन्हांकित करा',
    office: 'कार्यालय:',
    empowering: 'शाश्वत आणि नफ्याच्या भविष्यासाठी एआय-आधारित माहितीने शेतकऱ्यांना सक्षम करणे.',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    advisory: 'ஆலோசனை',
    weather: 'வானிலை',
    market: 'சந்தை',
    yojana: 'யோஜனா உதவி',
    myDashboard: 'என் டாஷ்போர்டு',
    login: 'உள்நுழைவு',
    overview: 'மேற்பார்வை',
    analytics: 'பகுப்பாய்வு',
    myFarm: 'என் பண்ணை',
    cropCalendar: 'பயிர் காலண்டர்',
    cropAdvisory: 'பயிர் ஆலோசனை',
    voiceAssistant: 'குரல் கேள்வி-பதில்',
    plantDoctor: 'தாவர மருத்துவர்',
    marketPrices: 'சந்தை விலை',
    govtSchemes: 'அரசு திட்டங்கள்',
    msp: 'குறைந்தபட்ச ஆதரவு விலை',
    communityForum: 'சமூக மன்றம்',
    soilLabs: 'மண் ஆய்வகங்கள்',
    fertilizerCalc: 'உரம் கணக்கீடு',
    yieldPredictor: 'மகசூல் கணிப்பான்',
    agriShorts: 'வேளாண் ஷார்ட்ஸ்',
    cropLifecycle: 'பயிர் வாழ்க்கைச் சுழற்சி',
    traceability: 'கண்காணிப்பு',
    settings: 'அமைப்புகள்',
    signOut: 'வெளியேறு',
    signingOut: 'வெளியேறுகிறது...',
    platform: 'தளம்',
    resources: 'வளங்கள்',
    contact: 'தொடர்பு',
    aiAdvisory: 'ஏஐ ஆலோசனை',
    weatherForecast: 'வானிலை முன்னறிவிப்பு',
    farmingBlog: 'விவசாய வலைப்பதிவு',
    cropGuides: 'பயிர் வழிகாட்டிகள்',
    community: 'சமூகம்',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    termsOfService: 'சேவை விதிமுறைகள்',
    notifications: 'அறிவிப்புகள்',
    unread: 'படிக்காதவை',
    markAllRead: 'அனைத்தையும் படித்ததாக மாற்று',
    office: 'அலுவலகம்:',
    empowering: 'நிலைத்த மற்றும் லாபகரமான எதிர்காலத்திற்காக விவசாயிகளை ஏஐ வழிநடத்தலால் வலுப்படுத்துதல்.',
    aiPoweredFarmingAssistant: 'ஏஐ சார்ந்த விவசாய உதவியாளர்',
    farmingMade: 'விவசாயத்தை',
    smarterBetter: 'மேலும் புத்திசாலி & சிறந்ததாக',
    heroSubtitle: 'உடனடி ஏஐ தகவல்களால் உங்கள் விவசாயத்தை வலுப்படுத்துங்கள். துல்லியமான வானிலை, மண் ஆரோக்கியம் மற்றும் சந்தை போக்குகளை உடனே பெறுங்கள்.',
    startForFree: 'இலவசமாக தொடங்குங்கள்',
    signIn: 'உள்நுழையவும்',
    verifiedData: 'சரிபார்க்கப்பட்ட தரவு',
    accuracy95: '95% துல்லியம்',
    cropHealthCard: 'பயிர் ஆரோக்கியம்',
    wheatField2: 'கோதுமை வயல் #2',
    nitrogenLevel: 'நைட்ரஜன் நிலை',
    optimalRange: 'சிறந்த வரம்பு',
    temp: 'வெப்பநிலை',
    sunny: 'வெயில்',
    pestRisk: 'பூச்சி அபாயம்',
    lowSafe: 'குறைவு (பாதுகாப்பானது)',
    marketPrice: 'சந்தை விலை',
    coreModules: 'முக்கிய அம்சங்கள்',
    everythingYouNeed: 'உங்களுக்கு தேவையான அனைத்தும்',
    farmSmarter: 'புத்திசாலி விவசாயத்துக்கு',
    featuresSubtitle: 'சிறு மற்றும் நடுத்தர விவசாயிகளுக்கான முழுமையான ஏஐ கருவிகள்.',
    openFeature: 'அம்சத்தை திற',
    weatherIntelligence: 'வானிலை நுண்ணறிவு',
    weatherIntelligenceDesc: 'பாசனம் மற்றும் பூச்சி கட்டுப்பாட்டுக்கு நேரடி முன்னறிவிப்புகள்.',
    soilHealthEngine: 'மண் ஆரோக்கிய இயந்திரம்',
    soilHealthEngineDesc: 'மண் அறிக்கைகளை பதிவேற்றி தனிப்பயன் உர ஆலோசனையை பெறுங்கள்.',
    marketPriceDashboard: 'சந்தை விலை டாஷ்போர்டு',
    marketPriceDashboardDesc: 'நல்ல விற்பனை முடிவுகளுக்கு நேரடி மண்டி விலை தகவல்.',
    pestDiseaseDiagnosis: 'பூச்சி & நோய் கண்டறிதல்',
    pestDiseaseDiagnosisDesc: 'ஏஐ படப்பகுப்பு மூலம் நோய்களை அடையாளம் காணுங்கள்.',
    multilingualSupport: 'பல்மொழி ஆதரவு',
    multilingualSupportDesc: 'தமிழ், ஹிந்தி, தெலுங்கு உள்ளிட்ட மொழிகளில் ஆலோசனை.',
    cropHealthMonitoring: 'பயிர் ஆரோக்கிய கண்காணிப்பு',
    cropHealthMonitoringDesc: 'வளர்ச்சி கட்டங்களை கண்காணித்து சரியான நேரத்தில் நடவடிக்கை எடுக்கவும்.',
    farmersEmpowered: 'சக்திவாய்ந்த விவசாயிகள்',
    acresMonitored: 'கண்காணிக்கப்பட்ட ஏக்கர்கள்',
    yieldIncrease: 'விளைச்சல் உயர்வு',
    waterSaved: 'சேமிக்கப்பட்ட நீர்',
    aerospaceTechnology: 'மேம்பட்ட தொழில்நுட்பம்',
    intelligenceBehind: 'ஒவ்வொரு விளைச்சலுக்கும் பின்னால்',
    everyHarvest: 'நுண்ணறிவு உள்ளது',
    advancedSubtitle: 'ஏஐ, ஐஓடி, செயற்கைக்கோள் தரவுகளை பயன்படுத்தி துல்லிய விவசாயத்தை கொண்டு வருகிறோம்.',
    exploreEngine: 'தொழில்நுட்பத்தை அறிக',
    deepLearningModels: 'டீப் லெர்னிங் மாடல்கள்',
    deepLearningModelsDesc: 'பயிர் நோய்களை முன்கூட்டியே கண்டறியும் உயர் துல்லிய மாடல்கள்.',
    satelliteRemoteSensing: 'செயற்கைக்கோள் கண்காணிப்பு',
    satelliteRemoteSensingDesc: 'NDVI மற்றும் மண் ஈரப்பதம் போன்ற விரிவான தகவல்கள்.',
    bigDataAnalytics: 'பெரும் தரவு பகுப்பாய்வு',
    bigDataAnalyticsDesc: 'உங்கள் பண்ணைக்கு ஏற்ற உள்ளூர் கணிப்புகள் உருவாக்கம்.',
    iotConnectivity: 'IoT இணைப்பு',
    iotConnectivityDesc: 'ஸ்மார்ட் சென்சார் மற்றும் தானியங்கி பாசன இணைப்பு.',
    howItWorksTitle: 'இது எப்படி செயல்படுகிறது',
    howItWorksSubtitle: 'மூன்று எளிய படிகளில் நிபுணர் ஆலோசனை பெறுங்கள்.',
    uploadData: 'தரவை பதிவேற்று',
    uploadDataDesc: 'பயிர்/மண் புகைப்படத்தை பாதுகாப்பாக பதிவேற்றவும்.',
    aiAnalysis: 'ஏஐ பகுப்பாய்வு',
    aiAnalysisDesc: 'மில்லியன் கணக்கான தரவுகளுடன் ஒப்பிட்டு பிரச்சினைகளை கண்டறிகிறது.',
    getResults: 'முடிவுகளை பெறுங்கள்',
    getResultsDesc: 'உங்கள் மொழியில் உடனடி, செயல்படுத்தக்கூடிய ஆலோசனை.',
    joinAgriRevolution: 'விவசாய புரட்சியில் இணைக',
    readyToTransform: 'உங்கள் விளைச்சலை மாற்ற',
    yourHarvest: 'தயாரா?',
    howItWorksCtaSubtitle: '2.8 லட்சம் விவசாயிகள் ஏற்கனவே SmartAgriSense உடன் வளர்ந்து வருகின்றனர்.',
    getStartedForFree: 'இலவசமாக தொடங்குங்கள்',
    contactRuralAdvisors: 'கிராமிய ஆலோசகர்களை தொடர்புகொள்ளுங்கள்',
  },
  te: {
    dashboard: 'డ్యాష్‌బోర్డ్',
    advisory: 'సలహా',
    weather: 'వాతావరణం',
    market: 'మార్కెట్',
    yojana: 'యోజన సహాయక్',
    myDashboard: 'నా డ్యాష్‌బోర్డ్',
    login: 'లాగిన్',
    overview: 'సారాంశం',
    analytics: 'విశ్లేషణలు',
    myFarm: 'నా వ్యవసాయం',
    cropCalendar: 'పంట క్యాలెండర్',
    cropAdvisory: 'పంట సలహా',
    voiceAssistant: 'వాయిస్ ప్రశ్నోత్తరాలు',
    plantDoctor: 'పంట డాక్టర్',
    marketPrices: 'మార్కెట్ ధరలు',
    govtSchemes: 'ప్రభుత్వ పథకాలు',
    msp: 'కనిష్ఠ మద్దతు ధర',
    communityForum: 'సముదాయ వేదిక',
    soilLabs: 'మట్టి ల్యాబ్స్',
    fertilizerCalc: 'ఎరువు కాల్క్',
    yieldPredictor: 'దిగుబడి అంచనా',
    agriShorts: 'వ్యవసాయ షార్ట్స్',
    cropLifecycle: 'పంట జీవిత చక్రం',
    traceability: 'గుర్తింపు',
    settings: 'సెట్టింగ్స్',
    signOut: 'సైన్ అవుట్',
    signingOut: 'సైన్ అవుట్ అవుతోంది...',
    platform: 'ప్లాట్‌ఫారమ్',
    resources: 'వనరులు',
    contact: 'సంప్రదింపు',
    aiAdvisory: 'ఎఐ సలహా',
    weatherForecast: 'వాతావరణ సూచన',
    farmingBlog: 'వ్యవసాయ బ్లాగ్',
    cropGuides: 'పంట మార్గదర్శకాలు',
    community: 'సముదాయం',
    privacyPolicy: 'గోప్యతా విధానం',
    termsOfService: 'సేవా నిబంధనలు',
    notifications: 'నోటిఫికేషన్లు',
    unread: 'చదవనివి',
    markAllRead: 'అన్నింటినీ చదివినట్లు గుర్తించు',
    office: 'కార్యాలయం:',
    empowering: 'సుస్థిరమైన మరియు లాభదాయకమైన భవిష్యత్తు కోసం రైతులకు AI ఆధారిత సహాయం అందించడం.',
    aiPoweredFarmingAssistant: 'ఏఐ ఆధారిత వ్యవసాయ సహాయకుడు',
    farmingMade: 'వ్యవసాయాన్ని',
    smarterBetter: 'ఇంకా స్మార్ట్ & మెరుగ్గా',
    heroSubtitle: 'రియల్‌టైమ్ ఏఐ సమాచారం ద్వారా మీ వ్యవసాయాన్ని బలోపేతం చేయండి.',
    startForFree: 'ఉచితంగా ప్రారంభించండి',
    signIn: 'సైన్ ఇన్',
    verifiedData: 'ధృవీకరించిన డేటా',
    accuracy95: '95% ఖచ్చితత్వం',
    cropHealthCard: 'పంట ఆరోగ్యం',
    wheatField2: 'గోధుమ పొలం #2',
    nitrogenLevel: 'నైట్రోజన్ స్థాయి',
    optimalRange: 'అత్యుత్తమ పరిధి',
    temp: 'ఉష్ణోగ్రత',
    sunny: 'ఎండగా',
    pestRisk: 'పురుగు ప్రమాదం',
    lowSafe: 'తక్కువ (సురక్షితం)',
    marketPrice: 'మార్కెట్ ధర',
    coreModules: 'ప్రధాన మాడ్యూల్స్',
    everythingYouNeed: 'మీకు అవసరమైన ప్రతిదీ',
    farmSmarter: 'స్మార్ట్ వ్యవసాయం కోసం',
    featuresSubtitle: 'చిన్న రైతుల కోసం రూపొందించిన పూర్తి ఏఐ సాధనాలు.',
    openFeature: 'ఫీచర్ తెరవండి',
    weatherIntelligence: 'వాతావరణ ఇంటెలిజెన్స్',
    weatherIntelligenceDesc: 'నీటిపారుదల, పురుగు నియంత్రణకు రియల్‌టైమ్ సూచనలు.',
    soilHealthEngine: 'నేల ఆరోగ్య ఇంజిన్',
    soilHealthEngineDesc: 'నేల నివేదిక ఆధారంగా వ్యక్తిగత ఎరువు సూచనలు పొందండి.',
    marketPriceDashboard: 'మార్కెట్ ధర డ్యాష్‌బోర్డ్',
    marketPriceDashboardDesc: 'మంచి అమ్మకాల నిర్ణయాల కోసం లైవ్ మండీ ధరలు.',
    pestDiseaseDiagnosis: 'పురుగు & వ్యాధి గుర్తింపు',
    pestDiseaseDiagnosisDesc: 'ఏఐ ఆధారిత ఇమేజ్ విశ్లేషణతో పంట వ్యాధులు గుర్తించండి.',
    multilingualSupport: 'బహుభాషా మద్దతు',
    multilingualSupportDesc: 'తెలుగు, హిందీ, తమిళం మరియు ఇతర భాషల్లో సలహా.',
    cropHealthMonitoring: 'పంట ఆరోగ్య మానిటరింగ్',
    cropHealthMonitoringDesc: 'పంట దశలను ట్రాక్ చేసి సమయానికి చర్యలు తీసుకోండి.',
    farmersEmpowered: 'శక్తివంతమైన రైతులు',
    acresMonitored: 'పర్యవేక్షించిన ఎకరాలు',
    yieldIncrease: 'దిగుబడి పెరుగుదల',
    waterSaved: 'నీటి పొదుపు',
    aerospaceTechnology: 'ఆధునిక సాంకేతికత',
    intelligenceBehind: 'ప్రతి దిగుబడి వెనుక',
    everyHarvest: 'తెలివైన విశ్లేషణ',
    advancedSubtitle: 'ఏఐ, ఐఓటి, ఉపగ్రహ డేటాతో ఖచ్చితమైన వ్యవసాయం అందిస్తున్నాం.',
    exploreEngine: 'టెక్నాలజీ తెలుసుకోండి',
    deepLearningModels: 'డీప్ లెర్నింగ్ మోడల్స్',
    deepLearningModelsDesc: 'పంట వ్యాధులను ముందుగానే గుర్తించే అధిక ఖచ్చితత్వ మోడల్స్.',
    satelliteRemoteSensing: 'ఉపగ్రహ రిమోట్ సెన్సింగ్',
    satelliteRemoteSensingDesc: 'NDVI, నేల తేమపై విశ్లేషణాత్మక సమాచారం.',
    bigDataAnalytics: 'బిగ్ డేటా అనలిటిక్స్',
    bigDataAnalyticsDesc: 'మీ ఫారంకు సరిపోయే స్థానిక అంచనాలు.',
    iotConnectivity: 'IoT కనెక్టివిటీ',
    iotConnectivityDesc: 'స్మార్ట్ సెన్సర్లు, ఆటోమేటెడ్ ఇరిగేషన్ సిస్టమ్‌లతో కనెక్షన్.',
    howItWorksTitle: 'ఇది ఎలా పనిచేస్తుంది',
    howItWorksSubtitle: 'మూడు సులభ దశల్లో నిపుణుల సలహా పొందండి.',
    uploadData: 'డేటా అప్‌లోడ్ చేయండి',
    uploadDataDesc: 'పంట/నేల ఫోటోను సురక్షితంగా అప్‌లోడ్ చేయండి.',
    aiAnalysis: 'ఏఐ విశ్లేషణ',
    aiAnalysisDesc: 'లక్షల డేటా పాయింట్లతో సమస్యలను గుర్తిస్తుంది.',
    getResults: 'ఫలితాలు పొందండి',
    getResultsDesc: 'మీ భాషలో తక్షణం అమలు చేయగల సలహా పొందండి.',
    joinAgriRevolution: 'వ్యవసాయ విప్లవంలో చేరండి',
    readyToTransform: 'మీ దిగుబడిని మార్చడానికి',
    yourHarvest: 'సిద్ధంగా ఉన్నారా?',
    howItWorksCtaSubtitle: 'ఇప్పటికే 2.8 లక్షల రైతులు SmartAgriSense తో ముందుకు సాగుతున్నారు.',
    getStartedForFree: 'ఉచితంగా ప్రారంభించండి',
    contactRuralAdvisors: 'గ్రామీణ సలహాదారులను సంప్రదించండి',
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    advisory: 'ಸಲಹೆ',
    weather: 'ಹವಾಮಾನ',
    market: 'ಮಾರುಕಟ್ಟೆ',
    yojana: 'ಯೋಜನಾ ಸಹಾಯಕ್',
    myDashboard: 'ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    login: 'ಲಾಗಿನ್',
    overview: 'ಅವಲೋಕನ',
    analytics: 'ವಿಶ್ಲೇಷಣೆ',
    myFarm: 'ನನ್ನ ಫಾರ್ಮ್',
    cropCalendar: 'ಬೆಳೆ ಕ್ಯಾಲೆಂಡರ್',
    cropAdvisory: 'ಬೆಳೆ ಸಲಹೆ',
    voiceAssistant: 'ವಾಯ್ಸ್ ಪ್ರಶ್ನೋತ್ತರ',
    plantDoctor: 'ಬೆಳೆ ವೈದ್ಯ',
    marketPrices: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
    govtSchemes: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    msp: 'ಕನಿಷ್ಠ ಬೆಂಬಲ ಬೆಲೆ',
    communityForum: 'ಸಮುದಾಯ ವೇದಿಕೆ',
    soilLabs: 'ಮಣ್ಣು ಪ್ರಯೋಗಾಲಯಗಳು',
    fertilizerCalc: 'ರಸಗೊಬ್ಬರ ಕ್ಯಾಲ್ಕ್',
    yieldPredictor: 'ಇಳುವರಿ ಮುನ್ಸೂಚನೆ',
    agriShorts: 'ಕೃಷಿ ಶಾರ್ಟ್ಸ್',
    cropLifecycle: 'ಬೆಳೆ ಜೀವನ ಚಕ್ರ',
    traceability: 'ಪತ್ತೆಹಚ್ಚುವಿಕೆ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    signOut: 'ಸೈನ್ ಔಟ್',
    signingOut: 'ಸೈನ್ ಔಟ್ ಆಗುತ್ತಿದೆ...',
    platform: 'ವೇದಿಕೆ',
    resources: 'ಸಂಪನ್ಮೂಲಗಳು',
    contact: 'ಸಂಪರ್ಕ',
    aiAdvisory: 'AI ಸಲಹೆ',
    weatherForecast: 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
    farmingBlog: 'ಕೃಷಿ ಬ್ಲಾಗ್',
    cropGuides: 'ಬೆಳೆ ಮಾರ್ಗದರ್ಶಿಗಳು',
    community: 'ಸಮುದಾಯ',
    privacyPolicy: 'ಗೌಪ್ಯತೆ ನೀತಿ',
    termsOfService: 'ಸೇವಾ ನಿಯಮಗಳು',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    unread: 'ಓದದವು',
    markAllRead: 'ಎಲ್ಲವನ್ನೂ ಓದಲಾಗಿದೆ ಎಂದು ಗುರುತುಮಾಡಿ',
    office: 'ಕಚೇರಿ:',
    empowering: 'ಶಾಶ್ವತ ಮತ್ತು ಲಾಭದಾಯಕ ಭವಿಷ್ಯಕ್ಕಾಗಿ AI ಆಧಾರಿತ ಒಳನೋಟಗಳಿಂದ ರೈತರಿಗೆ ಶಕ್ತಿ ನೀಡುವುದು.',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    advisory: 'পরামর্শ',
    weather: 'আবহাওয়া',
    market: 'বাজার',
    yojana: 'যোজনা সহায়ক',
    myDashboard: 'আমার ড্যাশবোর্ড',
    login: 'লগইন',
    overview: 'সংক্ষিপ্তসার',
    analytics: 'বিশ্লেষণ',
    myFarm: 'আমার খামার',
    cropCalendar: 'ফসল ক্যালেন্ডার',
    cropAdvisory: 'ফসল পরামর্শ',
    voiceAssistant: 'ভয়েস প্রশ্নোত্তর',
    plantDoctor: 'প্ল্যান্ট ডাক্তার',
    marketPrices: 'বাজার মূল্য',
    govtSchemes: 'সরকারি প্রকল্প',
    msp: 'ন্যূনতম সহায়ক মূল্য',
    communityForum: 'কমিউনিটি ফোরাম',
    soilLabs: 'মাটি ল্যাব',
    fertilizerCalc: 'সার ক্যালক',
    yieldPredictor: 'ফলন পূর্বাভাস',
    agriShorts: 'কৃষি শর্টস',
    cropLifecycle: 'ফসল জীবনচক্র',
    traceability: 'সনাক্তকরণ',
    settings: 'সেটিংস',
    signOut: 'সাইন আউট',
    signingOut: 'সাইন আউট হচ্ছে...',
    platform: 'প্ল্যাটফর্ম',
    resources: 'রিসোর্স',
    contact: 'যোগাযোগ',
    aiAdvisory: 'এআই পরামর্শ',
    weatherForecast: 'আবহাওয়ার পূর্বাভাস',
    farmingBlog: 'চাষাবাদ ব্লগ',
    cropGuides: 'ফসল গাইড',
    community: 'কমিউনিটি',
    privacyPolicy: 'গোপনীয়তা নীতি',
    termsOfService: 'সেবার শর্তাবলী',
    notifications: 'নোটিফিকেশন',
    unread: 'অপঠিত',
    markAllRead: 'সবগুলো পঠিত হিসেবে চিহ্নিত করুন',
    office: 'অফিস:',
    empowering: 'টেকসই ও লাভজনক ভবিষ্যতের জন্য এআই-চালিত তথ্য দিয়ে কৃষকদের শক্তিশালী করা।',
  },
  pa: {
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    advisory: 'ਸਲਾਹ',
    weather: 'ਮੌਸਮ',
    market: 'ਮਾਰਕੀਟ',
    yojana: 'ਯੋਜਨਾ ਸਹਾਇਕ',
    myDashboard: 'ਮੇਰਾ ਡੈਸ਼ਬੋਰਡ',
    login: 'ਲੋਗਿਨ',
    overview: 'ਸੰਖੇਪ',
    analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    myFarm: 'ਮੇਰਾ ਫਾਰਮ',
    cropCalendar: 'ਫਸਲ ਕੈਲੰਡਰ',
    cropAdvisory: 'ਫਸਲ ਸਲਾਹ',
    voiceAssistant: 'ਵੋਇਸ ਸਵਾਲ-ਜਵਾਬ',
    plantDoctor: 'ਪਲਾਂਟ ਡਾਕਟਰ',
    marketPrices: 'ਮੰਡੀ ਭਾਅ',
    govtSchemes: 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ',
    msp: 'ਘੱਟੋ-ਘੱਟ ਸਮਰਥਨ ਮੁੱਲ',
    communityForum: 'ਕਮਿਊਨਿਟੀ ਫੋਰਮ',
    soilLabs: 'ਮਿੱਟੀ ਲੈਬ',
    fertilizerCalc: 'ਖਾਦ ਕੈਲਕ',
    yieldPredictor: 'ਪੈਦਾਵਾਰ ਭਵਿੱਖਬਾਣੀ',
    agriShorts: 'ਖੇਤੀ ਸ਼ੌਰਟਸ',
    cropLifecycle: 'ਫਸਲ ਜੀਵਨ ਚੱਕਰ',
    traceability: 'ਟਰੇਸੇਬਿਲਟੀ',
    settings: 'ਸੈਟਿੰਗਜ਼',
    signOut: 'ਸਾਇਨ ਆਉਟ',
    signingOut: 'ਸਾਇਨ ਆਉਟ ਹੋ ਰਿਹਾ ਹੈ...',
    platform: 'ਪਲੇਟਫਾਰਮ',
    resources: 'ਸਰੋਤ',
    contact: 'ਸੰਪਰਕ',
    aiAdvisory: 'ਏਆਈ ਸਲਾਹ',
    weatherForecast: 'ਮੌਸਮ ਭਵਿੱਖਬਾਣੀ',
    farmingBlog: 'ਖੇਤੀ ਬਲਾਗ',
    cropGuides: 'ਫਸਲ ਗਾਈਡ',
    community: 'ਕਮਿਊਨਿਟੀ',
    privacyPolicy: 'ਪ੍ਰਾਈਵੇਸੀ ਪਾਲਿਸੀ',
    termsOfService: 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    unread: 'ਨਾ ਪੜ੍ਹੀਆਂ',
    markAllRead: 'ਸਭ ਨੂੰ ਪੜ੍ਹਿਆ ਨਿਸ਼ਾਨ ਲਗਾਓ',
    office: 'ਦਫ਼ਤਰ:',
    empowering: 'ਟਿਕਾਊ ਅਤੇ ਲਾਭਕਾਰੀ ਭਵਿੱਖ ਲਈ ਕਿਸਾਨਾਂ ਨੂੰ AI ਆਧਾਰਿਤ ਜਾਣਕਾਰੀ ਨਾਲ ਸਸ਼ਕਤ ਕਰਨਾ।',
  },
};

function parseLanguageFromValue(value: string | null | undefined): SiteLanguageCode {
  const normalized = (value || '').toLowerCase();
  if (normalized.startsWith('hi') || normalized.includes('हिंदी')) return 'hi';
  if (normalized.startsWith('mr') || normalized.includes('मराठी')) return 'mr';
  if (normalized.startsWith('ta') || normalized.includes('தமிழ்')) return 'ta';
  if (normalized.startsWith('te') || normalized.includes('తెలుగు')) return 'te';
  if (normalized.startsWith('kn') || normalized.includes('ಕನ್ನಡ')) return 'kn';
  if (normalized.startsWith('bn') || normalized.includes('বাংলা')) return 'bn';
  if (normalized.startsWith('pa') || normalized.includes('ਪੰਜਾਬੀ')) return 'pa';
  return 'en';
}

export function readSiteLanguage(): SiteLanguageCode {
  if (typeof window === 'undefined') {
    return 'en';
  }

  try {
    const direct = localStorage.getItem(APP_LANGUAGE_KEY);
    if (direct) {
      return parseLanguageFromValue(direct);
    }

    const rawSettings = localStorage.getItem(APP_SETTINGS_KEY);
    if (!rawSettings) {
      return 'en';
    }

    const settings = JSON.parse(rawSettings) as { language?: string };
    return parseLanguageFromValue(settings.language);
  } catch {
    return 'en';
  }
}

function syncHtmlLanguage(language: SiteLanguageCode) {
  if (typeof document === 'undefined') {
    return;
  }
  document.documentElement.lang = HTML_LANG_CODES[language] ?? 'en';
}

export function persistSiteLanguage(language: SiteLanguageCode) {
  if (typeof window === 'undefined') {
    return;
  }

  try {
    localStorage.setItem(APP_LANGUAGE_KEY, language);

    const rawSettings = localStorage.getItem(APP_SETTINGS_KEY);
    const settings = rawSettings ? (JSON.parse(rawSettings) as Record<string, unknown>) : {};
    settings.language = LANGUAGE_LABELS[language];
    localStorage.setItem(APP_SETTINGS_KEY, JSON.stringify(settings));
  } catch {
    // Ignore storage failures.
  }

  syncHtmlLanguage(language);
  window.dispatchEvent(new Event(APP_LANGUAGE_EVENT));
}

export function getLanguageLabel(language: SiteLanguageCode): string {
  return LANGUAGE_LABELS[language] ?? LANGUAGE_LABELS.en;
}

export function getVoiceLanguageCode(language: SiteLanguageCode): string {
  const map: Record<SiteLanguageCode, string> = {
    en: 'en-IN',
    hi: 'hi-IN',
    mr: 'hi-IN',
    ta: 'ta-IN',
    te: 'te-IN',
    kn: 'kn-IN',
    bn: 'bn-IN',
    pa: 'hi-IN',
  };

  return map[language] ?? 'en-IN';
}

export function useSiteLanguage() {
  const [language, setLanguageState] = useState<SiteLanguageCode>('en');

  useEffect(() => {
    const next = readSiteLanguage();
    setLanguageState(next);
    syncHtmlLanguage(next);

    const handleChange = () => {
      const current = readSiteLanguage();
      setLanguageState(current);
      syncHtmlLanguage(current);
    };

    window.addEventListener('storage', handleChange);
    window.addEventListener(APP_LANGUAGE_EVENT, handleChange);

    return () => {
      window.removeEventListener('storage', handleChange);
      window.removeEventListener(APP_LANGUAGE_EVENT, handleChange);
    };
  }, []);

  const setLanguage = (next: SiteLanguageCode) => {
    setLanguageState(next);
    persistSiteLanguage(next);
  };

  const t = useMemo(() => {
    return (key: string, fallback?: string) => {
      return UI_TEXT[language]?.[key] ?? UI_TEXT.en[key] ?? fallback ?? key;
    };
  }, [language]);

  return { language, setLanguage, t };
}
