'use client';

import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { FileText, AlertTriangle, ShieldCheck, Scale, ChevronRight } from 'lucide-react';
import { useSiteLanguage } from '@/lib/siteLanguage';

const sections = [
    {
        id: '1',
        icon: FileText,
        title: '1. Acceptance of Terms',
        content: [
            'By accessing or using SmartAgriSense (“the Platform”), you agree to be bound by these Terms of Service and all applicable laws and regulations of India.',
            'If you are accessing the Platform on behalf of a Farmer Producer Organisation (FPO) or agricultural cooperative, you confirm that you have authority to bind that entity.',
            'SmartAgriSense reserves the right to update these terms at any time. Continued use of the Platform after changes constitutes acceptance of the revised terms.',
            'Users below 18 years of age must obtain consent from a parent or guardian before using this Platform.',
        ]
    },
    {
        id: '2',
        icon: ShieldCheck,
        title: '2. Use License & Permitted Use',
        content: [
            'SmartAgriSense grants you a limited, non-exclusive, non-transferable license to access and use the Platform for personal, non-commercial agricultural advisory purposes.',
            'You may download reports, guides, and certificates generated by the Platform for your personal farm records.',
            'You may not reverse engineer, decompile, scrape, or attempt to extract the underlying AI models, algorithms, or training data from this Platform.',
            'Commercial resale of Platform outputs (advisory reports, yield predictions, soil analyses) without written permission is strictly prohibited.',
            'Use of automated bots, scripts, or crawlers to access the Platform is not permitted.',
        ]
    },
    {
        id: '3',
        icon: AlertTriangle,
        title: '3. Disclaimer & Accuracy of Advisory',
        content: [
            'The AI advisory, crop recommendations, weather forecasts, and market price data on this Platform are provided for informational purposes only.',
            'Agricultural outcomes depend on a wide variety of uncontrollable factors including climate variability, soil conditions, seed quality, irrigation availability, and pest pressure. SmartAgriSense cannot guarantee specific yield outcomes.',
            'MSP rates and government scheme details are sourced from official CACP and state agriculture department publications. However, always verify critical financial decisions with your local Krishi Vigyan Kendra (KVK) or APMC.',
            'SmartAgriSense is not liable for any crop loss, financial loss, physical harm, or economic damage arising from following Platform recommendations.',
            'Pest/disease identification is based on AI models with stated accuracy rates. In case of severe infestations, consult a licensed agronomist.',
        ]
    },
    {
        id: '4',
        icon: FileText,
        title: '4. User Responsibilities',
        content: [
            'You are responsible for maintaining the security of your account credentials. Do not share your OTP or login session with others.',
            'Data you upload (crop images, soil test reports) must be your own and must not infringe on any third-party intellectual property rights.',
            'Forum posts and community contributions must be respectful, factual, and related to agriculture. Spam, misinformation, or abusive content will result in account suspension.',
            'You agree not to upload content that promotes harmful pesticides banned under India’s Schedule of Insecticides.',
            'You are responsible for ensuring that any scheme or loan applications initiated through the Platform are accurate and truthful.',
        ]
    },
    {
        id: '5',
        icon: Scale,
        title: '5. Government Schemes & Financial Information',
        content: [
            'Information about PM-KISAN, PMFBY, KCC, and other schemes is provided for awareness and guidance only.',
            'The Platform facilitates navigation to official government portals (pmkisan.gov.in, AgriStack, etc.) but does not directly process government disbursements.',
            'Loan EMI calculations are approximate and based on standard formulas. Final loan terms are determined by the respective bank or NBFC.',
            'SmartAgriSense is not a registered financial advisor or SEBI-registered entity. Market price information is not investment advice.',
        ]
    },
    {
        id: '6',
        icon: ShieldCheck,
        title: '6. Intellectual Property',
        content: [
            'All content on this Platform — including AI models, crop databases, UI designs, advisory algorithms, and knowledge base — is the intellectual property of SmartAgriSense Pvt. Ltd.',
            'The SmartAgriSense name, logo, and “Kisan Sahayak” brand are registered trademarks.',
            'User-generated content (forum posts, crop records) remains your property. By posting on the Platform, you grant SmartAgriSense a non-exclusive license to use anonymized versions to improve AI models.',
            'Any feedback, suggestions, or bug reports you submit may be used by SmartAgriSense without compensation.',
        ]
    },
    {
        id: '7',
        icon: AlertTriangle,
        title: '7. Limitation of Liability',
        content: [
            'To the maximum extent permitted by Indian law, SmartAgriSense’s total liability to you for any claim shall not exceed the subscription fees paid by you in the 3 months prior to the claim.',
            'SmartAgriSense is not liable for indirect, incidental, consequential, or punitive damages including loss of crop revenue, data loss, or business interruption.',
            'Platform downtime for maintenance, server failures, or force majeure events (natural disasters, internet outages, government restrictions) are excluded from liability.',
        ]
    },
    {
        id: '8',
        icon: Scale,
        title: '8. Governing Law & Dispute Resolution',
        content: [
            'These Terms shall be governed by and construed in accordance with the laws of India.',
            'Any disputes shall first be attempted to be resolved through mediation within 30 days of written notice.',
            'If mediation fails, disputes shall be subject to the exclusive jurisdiction of courts in Bangalore, Karnataka, India.',
            'For consumer grievances under the Consumer Protection Act 2019, you may contact our Grievance Officer at grievance@smartagrisense.com within 30 days of the issue.',
        ]
    },
];

export default function TermsPage() {
    const { language } = useSiteLanguage();
    const text = language === 'hi'
        ? {
            tos: 'सेवा की शर्तें',
            title: 'नियम और शर्तें',
            subtitle: 'SmartAgriSense का उपयोग करने से पहले इन शर्तों को ध्यान से पढ़ें।',
            updated: 'अंतिम अपडेट:',
            toc: 'विषय सूची',
        }
        : language === 'ta'
            ? {
                tos: 'சேவை விதிமுறைகள்',
                title: 'விதிமுறைகள் & நிபந்தனைகள்',
                subtitle: 'SmartAgriSense பயன்படுத்தும் முன் இந்த விதிமுறைகளை கவனமாக படிக்கவும்.',
                updated: 'கடைசியாக புதுப்பிக்கப்பட்டது:',
                toc: 'உள்ளடக்க அட்டவணை',
            }
            : language === 'te'
                ? {
                    tos: 'సేవా నిబంధనలు',
                    title: 'నియమాలు & షరతులు',
                    subtitle: 'SmartAgriSense ఉపయోగించే ముందు ఈ నిబంధనలను జాగ్రత్తగా చదవండి.',
                    updated: 'చివరి నవీకరణ:',
                    toc: 'విషయ సూచిక',
                }
        : {
            tos: 'Terms of Service',
            title: 'Terms & Conditions',
            subtitle: 'Please read these terms carefully before using SmartAgriSense. They govern your relationship with our Platform and define the rights and responsibilities of all parties.',
            updated: 'Last updated:',
            toc: 'Table of Contents',
        };
    return (
        <main className="min-h-screen flex flex-col pt-24">
            <Navbar />
            <div className="container py-16 max-w-4xl">
                {/* Header */}
                <div className="mb-12">
                    <div className="inline-flex items-center gap-2 px-4 py-2 bg-primary/10 text-primary rounded-full text-sm font-semibold mb-4">
                        <FileText className="h-4 w-4" />
                        {text.tos}
                    </div>
                    <h1 className="text-4xl font-extrabold mb-4">{text.title}</h1>
                    <p className="text-muted-foreground text-lg leading-relaxed">
                        {text.subtitle}
                    </p>
                    <div className="mt-4 flex items-center gap-4 text-sm text-muted-foreground">
                        <span>{text.updated} <strong className="text-foreground">March 1, 2026</strong></span>
                        <span>•</span>
                        <span>Governed by <strong className="text-foreground">Indian Law</strong></span>
                    </div>
                </div>

                {/* Quick Navigation */}
                <div className="mb-10 p-5 bg-muted/30 rounded-2xl border border-border">
                    <p className="text-sm font-semibold mb-3">{text.toc}</p>
                    <div className="grid sm:grid-cols-2 gap-2">
                        {sections.map(s => (
                            <a
                                key={s.id}
                                href={`#section-${s.id}`}
                                className="flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors"
                            >
                                <ChevronRight className="h-3.5 w-3.5 shrink-0" />
                                {s.title}
                            </a>
                        ))}
                    </div>
                </div>

                {/* Sections */}
                <div className="space-y-10">
                    {sections.map(s => (
                        <div key={s.id} id={`section-${s.id}`} className="scroll-mt-28">
                            <div className="flex items-center gap-3 mb-4">
                                <div className="h-10 w-10 bg-primary/10 rounded-xl flex items-center justify-center shrink-0">
                                    <s.icon className="h-5 w-5 text-primary" />
                                </div>
                                <h2 className="text-xl font-bold">{s.title}</h2>
                            </div>
                            <ul className="space-y-3">
                                {s.content.map((item, i) => (
                                    <li key={i} className="flex items-start gap-3 text-muted-foreground">
                                        <div className="h-1.5 w-1.5 rounded-full bg-primary/60 mt-2 shrink-0" />
                                        <span className="leading-relaxed">{item}</span>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    ))}
                </div>
            </div>
            <Footer />
        </main>
    );
}
